packaging_format = 2

id = "smithereen"
name = "Smithereen"
description.en = "Federated, ActivityPub-compatible social network server with friends, walls, and groups."
description.fr = "Serveur de réseau social fédéré, compatible avec ActivityPub, avec des amis, des murs et des groupes."

version = "0.5~ynh1"

maintainers = ["lapineige"]

[upstream]
license = "unlicense"
code = "https://github.com/YunoHost-Apps/Smithereen"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = false
ldap = "false"
sso = "false"
# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "100M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/example"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "en"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # Note that user-provided passwords questions are not automatically saved as setting
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]
    type = "mysql"

    [resources.apt]
    packages = "openjdk-17-jdk maven"
